services:
  - type: web
    name: burzh-beats-yandex-proxy
    runtime: node
    plan: free
    rootDir: pwa-proxy
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
